name: Modify Services

on:
  workflow_dispatch:
    inputs:
      services_jar_url:
        description: 'URL to download services.jar'
        required: true
      android_api_level:
        description: 'Android API level'
        required: true
        default: '34'
      core_patch:
        description: 'Core patch'
        required: true
        type: choice
        options:
         - apply
         - do_not_apply
        default: 'apply'
      custom_device_name:
        description: 'Custom device name (optional)'
        required: false
      custom_version:
        description: 'Custom version (optional)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt full-upgrade -y
        sudo apt install -y default-jdk zipalign p7zip-full python3 aria2

    - name: Download services.jar
      run: |
        curl -L -C - -o services.jar "${{ github.event.inputs.services_jar_url }}"
    - name: Check services.jar
      run: |
        file_size=$(stat -c%s "services.jar")
        if [ $file_size -lt 2000000 ]; then
          echo "Error: services.jar is too small. Download might have failed." >&2
          exit 1
        fi

    - name: Clone smali repository
      run: git clone --depth=1 https://github.com/JesusFreke/smali.git

    - name: Build smali and baksmali
      run: |
        cd smali
        ./gradlew build

    - name: Extract services.jar
      run: 7z x services.jar -oservices

    - name: Decompile services dex files if available
      run: |
        if [ -f services/classes.dex ]; then
          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} services/classes.dex -o services_classes
        else
          echo "services/classes.dex not found, skipping decompilation."
        fi
        if [ -f services/classes2.dex ]; then
          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} services/classes2.dex -o services_classes2
        else
          echo "services/classes2.dex not found, skipping decompilation."
        fi
        if [ -f services/classes3.dex ]; then
          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} services/classes3.dex -o services_classes3
        else
          echo "services/classes3.dex not found, skipping decompilation."
        fi
        if [ -f services/classes4.dex ]; then
          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} services/classes4.dex -o services_classes4
        else
          echo "services/classes4.dex not found, skipping decompilation."
        fi
        if [ -f services/classes5.dex ]; then
          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} services/classes5.dex -o services_classes5
        else
          echo "services/classes5.dex not found, skipping decompilation."
        fi

    - name: Backup smali files
      run: |
        cp -r services_classes services_classes_backup || echo "services_classes directory not found, skipping backup."
        cp -r services_classes2 services_classes2_backup || echo "services_classes2 directory not found, skipping backup."
        cp -r services_classes3 services_classes3_backup || echo "services_classes3 directory not found, skipping backup."
        cp -r services_classes4 services_classes4_backup || echo "services_classes4 directory not found, skipping backup."
        cp -r services_classes5 services_classes5_backup || echo "services_classes5 directory not found, skipping backup."

    - name: Modify services smali files with core patch
      if: ${{ github.event.inputs.core_patch == 'apply' }}
      run: |
        python3 services_patch.py

    - name: Modify services smali files without core patch
      if: ${{ github.event.inputs.core_patch == 'do_not_apply' }}
      run: |
        python3 nservices_patch.py

    - name: Recompile services dex files
      run: |
        if [ -d services_classes ]; then
          java -jar smali/smali/build/libs/smali.jar a -a ${{ github.event.inputs.android_api_level }} services_classes -o services/classes.dex
        else
          echo "services_classes directory not found, skipping recompilation."
        fi
        if [ -d services_classes2 ]; then
          java -jar smali/smali/build/libs/smali.jar a -a ${{ github.event.inputs.android_api_level }} services_classes2 -o services/classes2.dex
        else
          echo "services_classes2 directory not found, skipping recompilation."
        fi
        if [ -d services_classes3 ]; then
          java -jar smali/smali/build/libs/smali.jar a -a ${{ github.event.inputs.android_api_level }} services_classes3 -o services/classes3.dex
        else
          echo "services_classes3 directory not found, skipping recompilation."
        fi
        if [ -d services_classes4 ]; then
          java -jar smali/smali/build/libs/smali.jar a -a ${{ github.event.inputs.android_api_level }} services_classes4 -o services/classes4.dex
        else
          echo "services_classes4 directory not found, skipping recompilation."
        fi
        if [ -d services_classes5 ]; then
          java -jar smali/smali/build/libs/smali.jar a -a ${{ github.event.inputs.android_api_level }} services_classes5 -o services/classes5.dex
        else
          echo "services_classes5 directory not found, skipping recompilation."
        fi

    - name: Repack services.jar
      run: |
        # 从原始 services.jar 解压除 .dex 文件以外的其他文件
        7z x services.jar -oservices_temp "*.dex" -xr!*

        # 将重新编译的 .dex 文件移到临时目录
        mv services/classes.dex services_temp/
        mv services/classes2.dex services_temp/ || echo "classes2.dex not found, skipping."
        mv services/classes3.dex services_temp/ || echo "classes3.dex not found, skipping."
        mv services/classes4.dex services_temp/ || echo "classes4.dex not found, skipping."
        mv services/classes5.dex services_temp/ || echo "classes5.dex not found, skipping."

        # 使用 7z 将所有文件重新打包回 services.jar
        7z a -tzip services_new.jar -r services_temp/*

    - name: Upload modified services.jar
      uses: actions/upload-artifact@v3
      with:
        name: modified_services.jar
        path: services_new.jar
