name: Modify Framework and Services

on:
  workflow_dispatch:
    inputs:
      framework_jar_url:
        description: 'URL to download framework.jar'
        required: false
      services_jar_url:
        description: 'URL to download services.jar'
        required: false
      miui_services_jar_url:
        description: 'URL to download miui-services.jar'
        required: false
      miui_framework_jar_url:
        description: 'URL to download miui-framework.jar'
        required: false
      android_api_level:
        description: 'Android API level'
        required: true
        default: '30'
      core_patch:
        description: 'Core patch'
        required: true
        type: choice
        options:
         - apply
         - do_not_apply
        default: 'apply'
      custom_device_name:
        description: 'Custom device name (optional)'
        required: false
      custom_version:
        description: 'Custom version (optional)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt full-upgrade -y
        sudo apt install -y default-jdk zipalign p7zip-full python3 aria2

    - name: Download framework.jar
      if: ${{ inputs.framework_jar_url != '' }}
      run: |
        curl -L -C - -o framework.jar "${{ github.event.inputs.framework_jar_url }}"
    - name: Check framework.jar
      if: ${{ inputs.framework_jar_url != '' }}
      run: |
        file_size=$(stat -c%s "framework.jar")
        if [ $file_size -lt 2000000 ]; then
          echo "Error: framework.jar is too small. Download might have failed." >&2
          exit 1
        fi

    - name: Download services.jar
      if: ${{ inputs.services_jar_url != '' }}
      run: |
        curl -L -C - -o services.jar "${{ github.event.inputs.services_jar_url }}"
    - name: Check services.jar
      if: ${{ inputs.services_jar_url != '' }}
      run: |
        file_size=$(stat -c%s "services.jar")
        if [ $file_size -lt 2000000 ]; then
          echo "Error: services.jar is too small. Download might have failed." >&2
          exit 1
        fi

    - name: Download miui-services.jar
      if: ${{ inputs.miui_services_jar_url != '' }}
      run: |
        curl -L -C - -o miui-services.jar "${{ github.event.inputs.miui_services_jar_url }}"
    - name: Check miui-services.jar
      if: ${{ inputs.miui_services_jar_url != '' }}
      run: |
        file_size=$(stat -c%s "miui-services.jar")
        if [ $file_size -lt 1000000 ]; then
          echo "Error: miui-services.jar is too small. Download might have failed." >&2
          exit 1
        fi

    - name: Download miui-framework.jar
      if: ${{ inputs.miui_framework_jar_url != '' }}
      run: |
        curl -L -C - -o miui-framework.jar "${{ github.event.inputs.miui_framework_jar_url }}"
    - name: Check miui-framework.jar
      if: ${{ inputs.miui_framework_jar_url != '' }}
      run: |
        file_size=$(stat -c%s "miui-framework.jar")
        if [ $file_size -lt 1000000 ]; then
          echo "Error: miui-framework.jar is too small. Download might have failed." >&2
          exit 1
        fi

    - name: Clone smali repository
      run: git clone --depth=1 https://github.com/JesusFreke/smali.git

    - name: Build smali and baksmali
      run: |
        cd smali
        ./gradlew build

    - name: Extract framework.jar
      if: ${{ inputs.framework_jar_url != '' }}
      run: 7z x framework.jar -oframework

    - name: Extract services.jar
      if: ${{ inputs.services_jar_url != '' }}
      run: 7z x services.jar -oservices

    - name: Extract miui-services.jar
      if: ${{ inputs.miui_services_jar_url != '' }}
      run: 7z x miui-services.jar -omiui_services

    - name: Extract miui-framework.jar
      if: ${{ inputs.miui_framework_jar_url != '' }}
      run: 7z x miui-framework.jar -omiui_framework

    - name: Decompile framework dex files if available
      if: ${{ inputs.framework_jar_url != '' }}
      run: |
        if [ -f framework/classes.dex ]; then
          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} framework/classes.dex -o classes
        else
          echo "framework/classes.dex not found, skipping decompilation."
        fi
        if [ -f framework/classes2.dex ]; then
          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} framework/classes2.dex -o classes2
        else
          echo "framework/classes2.dex not found, skipping decompilation."
        fi
        if [ -f framework/classes3.dex ]; then
          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} framework/classes3.dex -o classes3
        else
          echo "framework/classes3.dex not found, skipping decompilation."
        fi
        if [ -f framework/classes4.dex ]; then
          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} framework/classes4.dex -o classes4
        else
          echo "framework/classes4.dex not found, skipping decompilation."
        fi
        if [ -f framework/classes5.dex ]; then
          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} framework/classes5.dex -o classes5
        else
          echo "framework/classes5.dex not found, skipping decompilation."
        fi

    - name: Decompile services dex files if available
      if: ${{ inputs.services_jar_url != '' }}
      run: |
        if [ -f services/classes.dex ]; then
          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} services/classes.dex -o services_classes
        else
          echo "services/classes.dex not found, skipping decompilation."
        fi
        if [ -f services/classes2.dex ]; then
          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} services/classes2.dex -o services_classes2
        else
          echo "services/classes2.dex not found, skipping decompilation."
        fi
        if [ -f services/classes3.dex ]; then
          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} services/classes3.dex -o services_classes3
        else
          echo "services/classes3.dex not found, skipping decompilation."
        fi
        if [ -f services/classes4.dex ]; then
          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} services/classes4.dex -o services_classes4
        else
          echo "services/classes4.dex not found, skipping decompilation."
        fi
        if [ -f services/classes5.dex ]; then
          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} services/classes5.dex -o services_classes5
        else
          echo "services/classes5.dex not found, skipping decompilation."
        fi

    - name: Decompile miui-services dex file
      if: ${{ inputs.miui_services_jar_url != '' }}
      run: |
        java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} miui_services/classes.dex -o miui_services_classes

        - name: Decompile miui-framework dex file
      if: ${{ inputs.miui_framework_jar_url != '' }}
      run: |
        java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} miui_framework/classes.dex -o miui_framework_classes

    - name: Apply core patch
      if: ${{ inputs.core_patch == 'apply' }}
      run: |
        # Apply the core patch logic here
        echo "Applying core patch..."

    - name: Build final artifacts
      run: |
        # Build your final artifacts here
        echo "Building final artifacts..."

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: framework-services-artifacts
        path: |
          framework.jar
          services.jar
          miui-services.jar
          miui-framework.jar
          classes
          classes2
          classes3
          classes4
          classes5
          services_classes
          services_classes2
          services_classes3
          services_classes4
          services_classes5
          miui_services_classes
          miui_framework_classes

